# .github/workflows/ci-cd.yml

name: Go-Notes CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Compile and Check for Errors
        run: go build -v ./...

      - name: Run Unit Tests
        run: go test -v ./...

  cd:
    needs: ci
    runs-on: ubuntu-latest
    continue-on-error: true # Adicionado: Permite que o job termine, apesar da falha de rede.

    steps:
      - name: Setup SSH Connection and Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Server to Known Hosts (Expected Failure)
        #run: ssh-keyscan -T 1 -H 192.168.56.101 >> ~/.ssh/known_hosts

      - name: Execute Deployment Script on VM (Expected Failure)
        run: |
          echo "Tentativa de conexao a 192.168.56.101. Esta etapa irá falhar por razões de rede (VM local)."
          ssh -o StrictHostKeyChecking=no edyezzy@192.168.56.101 'sudo /home/appuser/go-notes/deploy.sh'
